### ISSUE TITLE
Nice project - Issue

### ISSUE THREAD

**Issue by ijnrghjkdsmigywneig203** [Scr1pterLua/GhostWare#1]
Anti-recoil does not seem to work, any ETA on when it may be fixed? Thanks.

**Comment by Scr1pterLua** [comment]
Yea sorry iv been taking some time off il post the new thing rn

**Comment by Scr1pterLua** [comment]
> Anti-recoil does not seem to work, any ETA on when it may be fixed? Thanks.

fixed
